version: '3'
services:

    ## Banco ##
    db:
        image: postgres:13
        ports:
            - "5433:5432"
        environment:
            TZ: America/Sao_Paulo
            PGTZ: America/Sao_Paulo
            POSTGRES_DB: testespassu
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgresql:/docker-entrypoint-initdb.d
        networks:
            - teste-network

    ## Aplicação ## 
    app:
        build: .
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/teste-spassu/
            - letsencrypt:/etc/letsencrypt
            - apache:/etc/apache2
        working_dir: /var/www/html/teste-spassu/
        ports:
            - "8000:80"
        extra_hosts:
            - "testespassu:127.0.0.1"
        environment:
            - TZ=America/Sao_Paulo
            - PGPASSWORD=postgres
            - PGUSER=postgres
            - PGDATABASE=testespassu
            - PGHOST=db
            - PGPORT=5432
        command: >
            bash -c "composer install &&
            composer update &&
            composer dumpautoload &&
            php artisan cache:clear &&
            php artisan config:clear &&
            php artisan view:clear &&
            php artisan migrate --seed &&
            npm install --verbose &&
            npm run dev &&
            chown -R www-data.root storage/ bootstrap/cache &&
            chmod -R 755 storage/ bootstrap/cache &&
            apachectl -D FOREGROUND"
        networks:
            - teste-network

volumes:
    postgresql:
    letsencrypt:
    apache:

networks:
    teste-network:
        driver: bridge
